FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /code

RUN mkdir -p /code/static /code/media

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN python manage.py collectstatic --noinput

EXPOSE 8000

CMD [
    "gunicorn",
    "--bind",
    "0.0.0.0:8000",
    "demo_project.wsgi:application"
]
